### ISSUE TITLE
Show yeoman output automatically

### ISSUE THREAD

**Issue by l0rd** [eclipse/theia-yeoman-plugin#2]
To see yeoman output when executing "Yeoman Wizard" a user needs to open the output view and select "Yeoman Generator" to see what is going on. 

The output of the plugin should be shown automatically as soon as `yeoman` is started without any manual interaction.

**Comment by vitaliy-guliy** [comment]
It seems this issue is not actual anymore, as the wizard always open the `Yeoman Generator` output.
